spring:
  application:
    name: tasks
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/example}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
security:
  jwt:
    secret-key: e9a6bfc521767ba5a2c7dc6242df3da26f8586aef53d6f947d6ab14473fb9965
    expiration-time: 1200000